language: php
php:
- 7.0
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: sh deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=http://plugins.svn.wordpress.org/block-layouts/